import { StyleSheet } from "react-native";
import { Colors } from "@/utils/Constants";
import { DS } from "@/theme/designSystem";

export const riderDeliveryStyles = StyleSheet.create({
  panel: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 8,
    borderTopWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 14,
    zIndex: 10,
  },
  panelCompact: {
    paddingHorizontal: 16,
  },
  handle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#E2E8F0",
    marginBottom: 12,
  },
  phaseHeader: {
    marginBottom: 12,
  },
  phaseRow: {
    marginBottom: 14,
  },
  phaseBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    marginBottom: 6,
  },
  phaseLabel: {
    color: DS.color.text,
    letterSpacing: -0.2,
  },
  phaseHint: {
    color: DS.color.textMuted,
    marginTop: 4,
    lineHeight: 17,
  },
  destCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: DS.color.border,
  },
  destIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  destIconPickup: {
    backgroundColor: "#ecfdf5",
    borderColor: "#bbf7d0",
  },
  destIconDrop: {
    backgroundColor: "#ffedd5",
    borderColor: "#fed7aa",
  },
  destBody: {
    flex: 1,
    marginLeft: 10,
    minWidth: 0,
  },
  destLabel: {
    color: DS.color.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.3,
    marginBottom: 2,
  },
  destAddress: {
    color: DS.color.text,
    lineHeight: 19,
  },
  destNavChip: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#eff6ff",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  navigateBtnLarge: {
    height: 50,
    borderRadius: 14,
    backgroundColor: Colors.tertiary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginBottom: 10,
    gap: 8,
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  contactMini: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: DS.color.border,
  },
  contactAvatarMini: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#ffedd5",
    alignItems: "center",
    justifyContent: "center",
  },
  meetLabel: {
    color: DS.color.textSoft,
  },
  contactName: {
    color: DS.color.text,
  },
  callBtnSmall: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#16a34a",
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtn: {
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  actionBtnText: {
    color: "#fff",
  },
  contactCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: DS.color.border,
  },
  contactAvatar: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#ffedd5",
    alignItems: "center",
    justifyContent: "center",
  },
  contactBody: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  callBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#16a34a",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  routeCard: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: DS.color.border,
  },
  navigateBtn: {
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.tertiary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginBottom: 12,
  },
  navigateBtnText: {
    color: "#fff",
    marginLeft: 8,
  },
  routeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  pickupDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#16a34a",
    marginTop: 4,
    marginRight: 10,
  },
  dropDot: {
    width: 10,
    height: 10,
    borderRadius: 2,
    backgroundColor: Colors.theme,
    marginTop: 4,
    marginRight: 10,
  },
  routeLine: {
    position: "absolute",
    left: 4,
    top: 16,
    width: 2,
    height: 28,
    backgroundColor: "#E2E8F0",
  },
  routeContent: {
    flex: 1,
    minWidth: 0,
  },
  routeLabel: {
    color: DS.color.textSoft,
    letterSpacing: 0.3,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  swipeContainer: {
    borderRadius: 14,
    height: 52,
    marginBottom: 4,
  },
  swipeRail: {
    backgroundColor: "transparent",
    height: 52,
    borderRadius: 14,
    borderWidth: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  swipeTitle: {
    fontWeight: "600",
  },
  swipeThumb: {
    borderRadius: 12,
    height: 44,
    borderWidth: 0,
  },
  chatFab: {
    position: "absolute",
    right: 14,
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 10,
  },
  statusPill: {
    position: "absolute",
    top: 12,
    alignSelf: "center",
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.82)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 6,
  },
  mapLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F7FB",
    paddingHorizontal: 24,
  },
});
