import { StyleSheet } from "react-native";
import { DS } from "@/theme/designSystem";

export const riderDeliveryStyles = StyleSheet.create({
  panel: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: DS.color.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 8,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 12,
    zIndex: 10,
  },
  handle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#e2e8f0",
    marginBottom: 12,
  },
  phaseRow: {
    marginBottom: 14,
  },
  phaseBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginBottom: 8,
  },
  phaseLabel: {
    color: DS.color.text,
  },
  contactCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: DS.color.border,
  },
  contactAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  contactBody: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  callBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#16a34a",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  routeCard: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: DS.color.border,
  },
  navigateBtn: {
    height: 44,
    borderRadius: 12,
    backgroundColor: "#0f766e",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginBottom: 12,
  },
  navigateBtnText: {
    color: "#fff",
    marginLeft: 8,
  },
  routeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  pickupDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#16a34a",
    marginTop: 4,
    marginRight: 10,
  },
  dropDot: {
    width: 10,
    height: 10,
    borderRadius: 2,
    backgroundColor: "#ef4444",
    marginTop: 4,
    marginRight: 10,
  },
  routeLine: {
    position: "absolute",
    left: 4,
    top: 16,
    width: 2,
    height: 28,
    backgroundColor: "#e2e8f0",
  },
  routeContent: {
    flex: 1,
    minWidth: 0,
  },
  routeLabel: {
    color: "#94a3b8",
    letterSpacing: 0.3,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  swipeContainer: {
    borderRadius: 14,
    height: 52,
    marginBottom: 4,
  },
  swipeRail: {
    backgroundColor: "transparent",
    height: 52,
    borderRadius: 14,
    borderWidth: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  swipeTitle: {
    fontWeight: "600",
  },
  swipeThumb: {
    borderRadius: 12,
    height: 44,
    borderWidth: 0,
  },
  chatFab: {
    position: "absolute",
    bottom: 340,
    right: 16,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 10,
  },
  statusPill: {
    position: "absolute",
    top: 12,
    alignSelf: "center",
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.82)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 6,
  },
});
